<template data-slot="title">Tasks - Dogfooding the framework</template>

<div class="tasks-app">
<h1>Tasks</h1>

{{#if isAdmin}}
<form method="POST" action="/tasks">
  <textarea type="text" name="title" placeholder="New task..." required autofocus></textarea>
  <button type="submit">Add</button>
</form>
{{/if}}

<ul>
{{#each tasks}}
  <li class="{{doneClass}}">
    <header>
      {{#if isAdmin}}
      <form method="POST" action="/tasks/{{id}}/toggle">
        <button type="submit">{{doneLabel}}</button>
      </form>
      {{/if}}
      {{#unless isAdmin}}{{doneLabel}}{{/unless}}
    </header>

    {{#unless shouldShowEditMode}}
    <section>{{title}}</section>
    {{/unless}}

    {{#if shouldShowEditMode}}
    <form method="PATCH" action="/tasks/{{id}}">
      <input type="hidden" value="{{id}}" name="id" />
      <textarea name="title">{{title}}</textarea>
      <button type="submit">Save</button>
    </form>
    {{/if}}

    {{#if isAdmin}}
    <footer>
      <form method="GET" action="/tasks">
        <input type="hidden" name="edit" value="{{id}}">
        <button type="submit">✎</button>
      </form>
      <form method="DELETE" action="/tasks/{{id}}">
        <button type="submit">🗑️</button>
      </form>
    </footer>
    {{/if}}
  </li>
{{/each}}
</ul>
</div>